#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_user:
  path: /user
  controller: App\Controller\UserController::index

app_admin:
  path: /admin
  controller: App\Controller\AdminController::index

app_homepage:
  path: /
  controller: App\Controller\HomepageController::index

user_registration_submit:
  path: /user/register
  controller: App\Controller\UserController::registerUserAction

